# Generated by Django 2.1.7 on 2019-04-11 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='StateAbbrev',
            field=models.ForeignKey(db_column='StateAbbrev', on_delete=django.db.models.deletion.CASCADE, to='homepage.States'),
        ),
        migrations.AlterField(
            model_name='states',
            name='StateAbbrev',
            field=models.CharField(db_column='StateAbbrev', max_length=2, primary_key=True, serialize=False),
        ),
    ]
